version: '3.1'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - "employee_network"
  app:
    image: petrova05/employee_app
    restart: always
    ports:
      - "8080:8080"
    networks:
      - "employee_network"
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/employee_db?allowPublicKeyRetrieval=true
    depends_on:
    - db
    volumes:
    - .m2:/root/.m2
networks:
  employee_network:


